version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - celery-worker
      - celery-beat

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=INFO --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo
    volumes:
      - .:/app


  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    volumes:
      - .:/app

#
#  flower:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: flower -A myapp
#    ports:
#      - "5555:5555"
#    depends_on:
#      - celery-worker
