version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - celery-worker
      - celery-beat

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=INFO --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo
    volumes:
      - .:/app


  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    volumes:
      - .:/app

#  flower:
#    image: mher/flower
#    ports:
#      - "5555:5555"
#    depends_on:
#      - celery-worker
