# Generated by Django 4.2.3 on 2024-03-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetopiclessonm2m',
            old_name='course',
            new_name='course_topic',
        ),
    ]
