# Generated by Django 4.2.3 on 2024-03-12 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_rename_course_coursetopiclessonm2m_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopicm2m',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_m2m2', to='course.course'),
        ),
        migrations.AlterField(
            model_name='coursetopicm2m',
            name='course_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_m2m2', to='course.coursetopic'),
        ),
        migrations.AlterField(
            model_name='coursetopicm2m',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_m2m2', to=settings.AUTH_USER_MODEL),
        ),
    ]
