# Generated by Django 4.2.3 on 2024-03-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_clesson_coursetopiclesson_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetopic',
            old_name='course_topic',
            new_name='topic',
        ),
    ]
