# Generated by Django 4.2.3 on 2024-04-10 08:25

from django.db import migrations, models
import django.db.models.manager
import src.common.constant


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_clesson_text_remove_clesson_video_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('api_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_kz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='course',
            name='course_trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('kz', 'KAZAKH'), ('ru', 'RUSSIAN')], db_index=True, default=src.common.constant.TestLang['KAZAKH'], max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_students',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
