# Generated by Django 4.2.3 on 2024-04-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.common.constant
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_PASSED', 'NOT_PASSED'), ('CONTINUE', 'CONTINUE'), ('PASSED', 'PASSED'), ('EXPIRED', 'EXPIRED')], db_index=True, default=src.common.constant.CourseStatus['NOT_PASSED'], max_length=12)),
                ('price', models.FloatField(default=0.0)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course"."user_course',
            },
        ),
    ]
