# Generated by Django 4.2.3 on 2023-08-19 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_answersign_commonquestion_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestionlevel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='lessonquestionlevel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
