# Generated by Django 4.2.3 on 2023-08-19 18:17

from django.db import migrations, models
import django.db.models.deletion
import src.common.constant
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_commonquestion_name_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlevel',
            name='choice',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CHOICE'), (1, 'MULTI_CHOICE')], db_index=True, default=src.common.constant.ChoiceType['CHOICE']),
        ),
        migrations.AlterField(
            model_name='studentquizz',
            name='quizz_type',
            field=models.CharField(choices=[('BY_LESSON', 'BY_LESSON'), ('FLASH_CARD', 'FLASH_CARD'), ('FULL_TEST_ENT', 'FULL_TEST_ENT'), ('INFINITY_QUIZ', 'INFINITY_QUIZ')], max_length=128),
        ),
        migrations.CreateModel(
            name='StudentQuizzQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_quizz_questions', to='quizzes.question')),
                ('student_quizz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_quizz_questions', to='quizzes.studentquizz')),
            ],
            options={
                'db_table': 'quizz"."student_quizz_question',
            },
        ),
    ]
