# Generated by Django 4.2.3 on 2023-08-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_lessonpair'),
        ('quizzes', '0008_studentscore_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizz',
            name='lesson_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_quizzes', to='common.lessonpair'),
        ),
    ]
