# Generated by Django 4.2.3 on 2023-08-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_lesson_course_type'),
        ('quizzes', '0009_studentquizz_lesson_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizzquestion',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_quizz_questions', to='common.lesson'),
        ),
    ]
