# Generated by Django 4.2.3 on 2023-08-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_studentquizzquestion_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquizz',
            name='quizz_type',
        ),
    ]
