# Generated by Django 4.2.3 on 2023-08-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_boughtpacket_user'),
        ('quizzes', '0013_studentquizz_packet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFullScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('unattem', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('number_of_question', models.IntegerField(default=0)),
                ('number_of_score', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_full_score', to='common.lesson')),
                ('student_quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_full_score', to='quizzes.studentquizz')),
            ],
            options={
                'db_table': 'quizz"."test_full_score',
            },
        ),
    ]
