# Generated by Django 4.2.3 on 2023-10-25 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_alter_packet_name_en_alter_packet_name_kz_and_more"),
        ("quizzes", "0014_testfullscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentquizz",
            name="quizz_duration",
            field=models.DurationField(blank=True, default="0", null=True),
        ),
        migrations.CreateModel(
            name="StudentQuizzFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(db_index=True, default=1)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("icon", models.FileField(upload_to="student_quizz/icon")),
                ("file", models.FileField(upload_to="student_quizz/file")),
                (
                    "course_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_type_files",
                        to="common.coursetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
