# Generated by Django 4.2.3 on 2023-10-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0015_studentquizz_quizz_duration_studentquizzfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentquizzfile",
            name="file_name",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
