# Generated by Django 4.2.3 on 2023-12-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0020_studentquizz_bought_packet"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_questions",
                to="quizzes.question",
            ),
        ),
    ]
