# Generated by Django 4.2.3 on 2024-01-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_alter_ratingtest_end_time_and_more'),
        ('quizzes', '0023_answer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_packets', to='common.packet')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_packets', to='quizzes.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
