# Generated by Django 4.2.3 on 2024-02-03 11:02

from django.db import migrations, models
import django.db.models.deletion
import src.common.constant


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_variantpacket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='common_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.commonquestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('SELECT', 'SELECT')], db_index=True, default=src.common.constant.QuestionType['DEFAULT'], max_length=11),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.variant'),
        ),
        migrations.AlterField(
            model_name='studentquizz',
            name='status',
            field=models.CharField(choices=[('NOT_PASSED', 'NOT_PASSED'), ('CONTINUE', 'CONTINUE'), ('PASSED', 'PASSED'), ('EXPIRED', 'EXPIRED')], db_index=True, default=src.common.constant.QuizzStatus['NOT_PASSED'], max_length=12),
        ),
    ]
