# Generated by Django 4.2.3 on 2024-02-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_alter_question_common_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.answersign'),
        ),
    ]
