# Generated by Django 4.2.3 on 2024-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0026_alter_answer_answer_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
