# Generated by Django 4.2.3 on 2024-03-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_coursetype_deleted_coursetypequizz_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0027_question_answer_question_question_answer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions_count', to='quizzes.question')),
                ('quizz_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions_count', to='common.coursetypequizz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions_count', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quizz"."user_questions_count',
            },
        ),
    ]
