# Generated by Django 4.2.3 on 2024-03-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_packet_second_price'),
        ('quizzes', '0028_userquestioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='common.lesson'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_score', to='common.lesson'),
        ),
    ]
