# Generated by Django 4.2.3 on 2024-06-20 20:55

from django.db import migrations, models
import src.common.constant


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_studentanswer_lesson_studentscore_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlevel',
            name='choice',
            field=models.IntegerField(choices=[(0, 'CHOICE'), (1, 'MULTI_CHOICE')], db_index=True, default=src.common.constant.ChoiceType['CHOICE']),
        ),
    ]
