# Generated by Django 4.2.3 on 2024-06-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_alter_questionlevel_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlevel',
            name='choice',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
