# Generated by Django 4.2.3 on 2023-08-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='tokenhistory',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='tokenversion',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uuid_field',
            new_name='uuid',
        ),
    ]
