# Generated by Django 4.2.3 on 2023-11-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_school"),
        ("accounts", "0004_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="accounts/icon"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.school",
            ),
        ),
    ]
