# Generated by Django 4.2.3 on 2023-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0006_alter_user_birthday_alter_user_city_alter_user_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_google",
            field=models.BooleanField(default=False),
        ),
    ]
