# Generated by Django 4.2.3 on 2024-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_balancehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
