# Generated by Django 4.2.3 on 2024-02-16 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_balancehistory_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_balance_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
