# Generated by Django 4.2.3 on 2025-11-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_telegramtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="telegramtoken",
            name="telegram_user_id",
            field=models.IntegerField(default=0),
        ),
    ]
