# Generated by Django 4.2.3 on 2025-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_telegram_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramtoken",
            name="telegram_user_id",
            field=models.CharField(default=0),
        ),
    ]
