# Generated by Django 4.2.3 on 2023-08-10 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(max_length=128)),
                ('txn_id', models.CharField(max_length=128)),
                ('account', models.CharField(max_length=128)),
                ('txnDate', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'integration"."kaspi_pay',
            },
        ),
    ]
