# Generated by Django 4.2.3 on 2023-08-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_kaspipay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspipay',
            name='txnDate',
            field=models.CharField(default='', max_length=128),
        ),
    ]
