# Generated by Django 4.2.3 on 2023-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_coursetype_lesson_coursetypelesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='test_type'),
        ),
    ]
