# Generated by Django 4.2.3 on 2023-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_coursetype_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='coursetype',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='coursetypelesson',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='kaspipay',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='lesson',
            name='math',
            field=models.BooleanField(default=False),
        ),
    ]
