# Generated by Django 4.2.3 on 2023-08-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_lessonpair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course_type',
        ),
    ]
