# Generated by Django 4.2.3 on 2023-08-26 07:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_coursetype_quizz_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_kz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='test_type')),
                ('color', models.CharField(max_length=128)),
                ('quizz_duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'common"."quizz_type',
            },
        ),
        migrations.CreateModel(
            name='CourseTypeQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=1)),
                ('main', models.BooleanField(default=False)),
                ('questions_number', models.IntegerField(default=0)),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_type_quizzes', to='common.coursetype')),
                ('quizz_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_type_quizzes', to='common.quizztype')),
            ],
            options={
                'db_table': 'common"."course_type_quizz',
                'unique_together': {('course_type', 'quizz_type')},
            },
        ),
    ]
