# Generated by Django 4.2.3 on 2023-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_quizztype_coursetypequizz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizztype',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='quizztype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='quiz-type'),
        ),
    ]
