# Generated by Django 4.2.3 on 2023-08-26 18:06

from django.db import migrations, models
import django.db.models.deletion
import src.common.constant
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_quizztype_options_alter_quizztype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('days', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('packet_type', models.CharField(choices=[('ONE_TIME', 'ONE_TIME'), ('MANY_TIMES', 'MANY_TIMES')], default=src.common.constant.PacketType['ONE_TIME'])),
                ('quantity', models.IntegerField(default=1)),
                ('quizz_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_type_quizzes', to='common.coursetypequizz')),
            ],
            options={
                'db_table': 'common"."packet',
            },
        ),
    ]
