# Generated by Django 4.2.3 on 2023-08-27 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_packet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.IntegerField(default=0)),
                ('packet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_packets', to='common.packet')),
            ],
            options={
                'db_table': 'common"."bought_packet',
            },
        ),
    ]
