# Generated by Django 4.2.3 on 2023-08-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_boughtpacket'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtpacket',
            name='remind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boughtpacket',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='boughtpacket',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
