# Generated by Django 4.2.3 on 2023-08-27 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0016_remove_boughtpacket_remind_boughtpacket_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtpacket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_packets', to=settings.AUTH_USER_MODEL),
        ),
    ]
