# Generated by Django 4.2.3 on 2023-10-24 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_lesson_choose_icon_lesson_icon"),
        ("common", "0018_packet_name_en_packet_name_kz_packet_name_ru"),
    ]

    operations = []
