# Generated by Django 4.2.3 on 2023-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_merge_20231024_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packet",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="packet",
            name="name_kz",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="packet",
            name="name_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
