# Generated by Django 4.2.3 on 2023-11-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0023_ratingtest_boughtpacket_rating_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingtest",
            name="end_time",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ratingtest",
            name="start_time",
            field=models.DateField(),
        ),
    ]
