# Generated by Django 4.2.3 on 2024-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('upload', models.ImageField(upload_to='image/')),
            ],
            options={
                'db_table': 'common"."question_answer_image',
            },
        ),
    ]
