# Generated by Django 4.2.3 on 2024-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_questionanswerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
