# Generated by Django 4.2.3 on 2024-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_coursetype_deleted_coursetypequizz_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='second_price',
            field=models.IntegerField(default=0),
        ),
    ]
