# Generated by Django 4.2.3 on 2024-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_packettesttype_packet_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
