# Generated by Django 4.2.3 on 2024-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_packet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspipay',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
