# Generated by Django 4.2.3 on 2025-01-06 06:31

from django.db import migrations, models
import src.common.constant


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_kaspipay_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="promo_type",
            field=models.CharField(
                choices=[("ORDINARY", "ORDINARY"), ("TELEGRAM", "TELEGRAM")],
                default=src.common.constant.PromoCodeType["ORDINARY"],
                max_length=11,
            ),
        ),
    ]
