# Generated by Django 4.2.3 on 2025-01-06 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0037_promocode_promo_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramPromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("telegram_user_id", models.CharField(default=0)),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.promocode",
                    ),
                ),
            ],
            options={
                "db_table": 'common"."telegram_promo_code',
            },
        ),
    ]
