# Generated by Django 4.2.3 on 2025-11-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0038_telegrampromocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrampromocode",
            name="promo_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_promo_code",
                to="common.promocode",
            ),
        ),
    ]
