name: Dev-Deploy
env:
  path: /var/www/full_test_hub_course_test/
  venv_file: venv
  env_file: .env
  branch: dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.10]

    steps:

    - name: Connect to remote server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.TESTENV_IP }}
        username: ${{ secrets.TESTENV_USER }}
        password: ${{ secrets.TESTENV_PASS }}
        port: ${{ secrets.TESTENV_SSH_PORT }}
        script: |
                cd "${{ env.path }}"
                echo директория "$PWD"
                chmod +x scripts/dev/*.sh
                for f in scripts/"${{ env.branch }}"/*.sh; do
                  bash "$f" || break
                done
